name: Testing libary

on: [workflow_dispatch, push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install

      - name: Run tests
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test
