name: Deploy Storybook

on: [workflow_dispatch, push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies 
        run: npm install --force

      - name: Run tests
        run: npm run test

      - name: Build Storybook
        run: CI=false npm run build-storybook

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: storybook-static
          token: ${{ secrets.TOKEN }}
